apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: catalog-items-deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: catalog-items-deployment
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 30
