apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-statefulset
spec:
  serviceName: "mongodb-service"
  selector:
    matchLabels:
      role: mongo
  template:
    metadata:
      labels:
        role: mongo
        environment: test
        replicaset: MainRepSet
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "mongoadmin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "Pass#word1"
          volumeMounts:
            - mountPath: /data/db
              name: mongo-data-storage
      volumes:
        - name: mongo-data-storage
          persistentVolumeClaim:
            claimName: mongo-data-claim

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    name: mongo
spec:
  clusterIP: None
  selector:
    role: mongo
  ports:
    - port: 27017
      targetPort: 27017
